name: genCoverage

on: 
  push:
    branches: [ master ]

jobs:
  build-genCoverage:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: install libs
        run: | 
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install gcovr
        
      - name: get tools version
        run: | 
          cmake --version
          make --version
          gcovr --version
        
      - name: build
        run: |
          cmake -B build/.dump -S .
          cmake --build build/.dump
          
      - name: test
        run: ctest

      - name: generate Docs/Coverage
        run: |
          mkdir Docs
          mkdir Docs/Coverage
          mkdir Docs/Coverage/Html
          mkdir Docs/Coverage/Sonarqube
      - run: >
          gcovr -r . -f src --html-details Docs/Coverage/Html/coverage.html 
          --sonarqube Docs/Coverage/Sonarqube/coverage.xml
        
      - name: Commit report
        run: |
          git config --global user.name 'Filip-Pesula'
          git config --global user.email 'filip.pesula@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git add -f Docs/
          git commit -am "Automated report"
          git push

