name: test


on: 
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: install libs
        run: | 
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install gcovr
        
      - name: get tools version
        run: | 
          cmake --version
          make --version
          gcovr --version
        
      - name: build
        run: |
          cmake -B build/.dump -S .
          cmake --build build/.dump
          
      - name: test
        run: ctest

      - name: coverage
        run: |
          gcovr -r . -f src --fail-under-line 80
